### ISSUE TITLE
[Regression] 9.2.0 leads to strange `InvalidCastException` when injecting in constructor

### ISSUE THREAD

**Issue by anonymous2585** [gustavopsantos/Reflex#81]
**Describe the bug**

After updating from Reflex 9.1.1 to 9.2.0, one of my service registered as singleton fail to inject due to a `FieldInjectorException: Specified cast is not valid.` exception.

The original exception is:
```
System.InvalidCastException: Specified cast is not valid.
  at (wrapper dynamic-method) System.Object.lambda_method(System.Runtime.CompilerServices.Closure,object[])
  at Reflex.Injectors.ConstructorInjector.Construct (System.Type concrete, Reflex.Core.Container container) [0x00094] in .\Packages\com.gustavopsantos.reflex\Injectors\ConstructorInjector.cs:29
  at Reflex.Core.Container.Construct (System.Type concrete) [0x00001] in .\Packages\com.gustavopsantos.reflex\Core\Container.cs:69 
  ...
```

It happens in a big project with ~140 services registered/injected as singleton.
When debugging (added logs in reflex code), I see that the exeption happen when one service (let say `ServiceG`) is injected in another by constructor:
```c#
public class ServiceG : IServiceG {

}
```

```c#
private IServiceB _serviceB;
private IServiceC _serviceC;
private IServiceD _serviceD;
private IServiceE _serviceE;
private IServiceF _serviceF;
private IServiceG _serviceG;

public ServiceA(
    IServiceB serviceB,
    IServiceC serviceC,
    IServiceD serviceD,
    IServiceE serviceE,
    IServiceF serviceF,
    IServiceG serviceG)
{
    _serviceB = serviceB;
    _serviceC = serviceC;
    _serviceD = serviceD;
    _serviceE = serviceE;
    _serviceF = serviceF;
    _serviceG = serviceG;
}
```

 - When I remove the argument from my constructor and use [Inject] attribute, I don't have the exception:
```csharp
[Inject] private IServiceG _serviceG;

public ServiceA(
    IServiceB serviceB,
    IServiceC serviceC,
    IServiceD serviceD,
    IServiceE serviceE,
    IServiceF serviceF)
{
    _serviceB = serviceB;
    _serviceC = serviceC;
    _serviceD = serviceD;
    _serviceE = serviceE;
    _serviceF = serviceF;
}
```

The exception happen [here](https://github.com/gustavopsantos/Reflex/blob/365fc5e40dd68f5c03619eda2d680bdf89a17145/Assets/Reflex/Injectors/ConstructorInjector.cs#L29).

This is strange, because this service (the `ServiceG`) has already been constructed and injected in others services, the instance is not null and just has to be injected in the service. When I debug the `arguments` variable, it contains all the services to inject in the right order.

When I replace
```csharp
var arguments = ArrayPool.Rent(constructorParametersLength);
```
with
```csharp
var arguments = new object[constructorParametersLength];
```
[here](https://github.com/gustavopsantos/Reflex/blob/365fc5e40dd68f5c03619eda2d680bdf89a17145/Assets/Reflex/Injectors/ConstructorInjector.cs#L20), I don't have the exception anymore!
I think something is wrong with ThreadStaticArrayPool, but hard to tell precisly what.

**Expected behavior**
Update from 9.1.1 to 9.2.0+ happen without breaking change.

**Desktop:**
 - Unity editor 6000.0.37f1

**Comment by gustavopsantos** [comment]
@anonymous2585 Thanks for reporting this issue, I believe its happening due to the recursion tree that is created when some topology of services exist, such as yours. I investigate more and create a unit-test to avoid this issue to regress in future. I will probably push a fix at most end of the week.

**Comment by anonymous2585** [comment]
I was able to reproduce in a toy project! As you said, I had to create a specific topology of services.

- [Download Reflex_Issue.zip](https://github.com/user-attachments/files/19320295/Reflex_Issue.zip)
- Open in Unity (6000.0.37f1 here, but should happen regardless of the version)
- Open Scene "Assets/Scenes/SampleScene"
- Press Play in the editor
- See the error

**Comment by gustavopsantos** [comment]
@anonymous2585 Fixed in https://github.com/gustavopsantos/Reflex/releases/tag/9.2.1, thanks again for reporting this issue.

**Comment by anonymous2585** [comment]
@gustavopsantos Thanks a lot for the quick fix! (And with new non-regression tests!)

Updated to 9.2.1 in our big project and now it works fine! 😃 

Just a small thing: I think you forgot to update the version in the package.json that is in the Reflex.9.2.1.unitypackage asset published in [the release](https://github.com/gustavopsantos/Reflex/releases/tag/9.2.1), it's still 9.2.0 😉

**Comment by gustavopsantos** [comment]
Ohh will fix that package.json now on the .unitypackage 👍
